QuivrHQ/quivr

files.py, loaders/html.py, main.py
https://github.com/StanGirard/quivr/pull/24
=> Add URL to Brain

README.md
Proposing a small Readme update with the goal of clarifying two small things that confused me during local install:
1. Clarify that the `Supabase API key` and `supabase_service_key` are referring to the `anon` `public` key found in the `Project API keys` section of the Supabase project.
2. Clarify that the "web interface" referenced is the `SQL Editor` in the Supabase dashboard.
=> Add clarification on Project API keys and web interface for migration scripts to Readme

files.py
When there is a unicode character in URL of website, your app fails.
I have added a try catch block and have printed the error in the standard output.
Fixes: https://github.com/StanGirard/quivr/issues/51
=> fix(51): Catch UnicodeEncodeError exception

v2/api.py
localhost.tiangolo.com domain is not necessary to enable cors since this domain is belong to tiangolo himself.
=> tiangolo domain is not necessary

question.py
When the user clicks Clear, the records in memory should be cleared at the same time. Otherwise, the memory record will always exist unless restarted.
=> Fix a bug where langchain memories were not being cleaned

README.md
At least one user was having difficulty cloning the repo because they didn't have an SSH key set up. The HTTPS git clone option will make it easier for non-technical users to test out this app.
=> add option to clone the repo without SSH key

backend/requirements.txt
When I upload a word doc I get the following error:
```
ModuleNotFoundError: No module named 'docx2txt'
```
Uploading a word doc succeeds:
=> add docx2txt package for uploading word docs

backend/Dockerfile
Some python package is too large, 15 seconds to download isn't sufficient, I expand this timeout to 100 seconds but you may varies this as you see fit. It's not affect overall build time for regular user, just expand the room for slow network user.
=> set pip timeout to 100 second (default 15)

frontend/app/components/ui/Toast/components/Toast.tsx, frontend/app/components/ui/Toast/hooks/useToastBuilder.ts
This PR use toast id for open status toggling, instead of index
=> feat(toast): use id for open status toggling

frontend/app/chat/page.tsx, frontend/package.json, frontend/yarn.lock
add speech to text in chat page use Web Speech API, from issue #81
=> add-speech-to-text-in-chat

backend/api.py, backend/parsers/odt.py
Adding a new loading in the backend to handle ODT files.
https://www.loom.com/share/c4a82aaf20e3434d80341bc1fd81aea7
=> ✨ new ODT document loader

frontend/Dockerfile
Use yarn.lock instead of package-lock.json in docker
=> chore(docker): use yarn.lock instead of package-lock.json

backend/llm/qa.py, backend/main.py
Excited to provide a basic source documents support!
Achieved by `return_source_documents` parameter of `ConversationalRetrievalChain` which attaches `source_documents` to `model_response`. File names parsed from documents metadata can be appended to the original answer.
Also a small wrapper of ConversationBufferMemory was added to suppress "One output key expected.." error (thanks to https://github.com/hwchase17/langchain/issues/5630#issuecomment-1574222564).
I tried to achieve it with minimal code changes. Let me know if there is anything unclear.
=> feat(chat): basic source documents support

frontend/app/(auth)/login/page.tsx, frontend/app/(auth)/logout/page.tsx, frontend/app/(auth)/signup/page.tsx, frontend/app/chat/[chatId]/page.tsx, frontend/app/chat/components/ChatMessages/ChatInput/index.tsx, frontend/app/chat/components/ChatMessages/index.tsx, frontend/app/chat/components/ChatsList/ChatsListItem.tsx, frontend/app/chat/components/ChatsList/NewChatButton.tsx, frontend/app/chat/components/ChatsList/index.tsx, frontend/app/chat/layout.tsx, frontend/app/components/Footer/index.tsx, frontend/app/components/NavBar/components/Header/index.tsx, frontend/app/config/page.tsx, frontend/app/explore/page.tsx, frontend/app/layout.tsx, frontend/app/upload/page.tsx, frontend/app/user/page.tsx
This PR makes some UX improvements on majorly the `/chat` page.
- Sticky navbar - to not have an arbitrary padding top on every page
- Sticky chatlist - to not having to scroll to the top everytime you want to switch to another chat
- Footer is now static instead of sticky 
- Chat input is also sticky to avoid overlap with the footer
https://github.com/StanGirard/quivr/assets/61308761/76251809-73a2-4522-ab49-880541a19e95
=> Sticky - chat list, navbar, chat input

frontend/app/chat/ChatsProvider/chats-provider.tsx, frontend/app/chat/ChatsProvider/hooks/useChats.ts, frontend/app/chat/ChatsProvider/hooks/useChatsContext.tsx, frontend/app/chat/ChatsProvider/hooks/useSpeech.ts, frontend/app/chat/ChatsProvider/types.ts, frontend/app/chat/[chatId]/page.tsx, frontend/app/chat/components/ChatMessages/ChatInput/MicButton.tsx, frontend/app/chat/components/ChatMessages/ChatInput/index.tsx, frontend/app/chat/components/ChatMessages/index.tsx, frontend/app/chat/components/ChatsList/index.tsx, frontend/app/chat/layout.tsx
This PR fixes my mistake of executing `useChats` hook everywhere by introducing a `useChatsContext` hook which has all the actions and states for all chat related stuff
- avoids multiple api calls
- fixes flickering when creating a new chat
=> use context to prevent having duplicate chat states

backend/parsers/audio.py
Have been creating a batch content uploading project that uses Quivr as a backend. Realised that multiple large mp4 files were not processed properly.
This was due to an exception thrown while executing `split_text` in audio.py file:
texts = text_splitter.split_text(transcript)
Exception thrown: `TypeError: expected string or bytes-like object, got 'OpenAIObject'`
This causes the temporary file to be left behind.
And the tmp directory rapidly ran out of space over time.
The fix:
Added a try/finally block to delete temporary file that's created. 
=> (fix) temporary audio file not removed.

backend/Dockerfile, backend/main.py, backend/requirements.txt, frontend/.gitignore, frontend/next.config.js, frontend/package.json, frontend/sentry.client.config.ts, frontend/sentry.edge.config.ts, frontend/sentry.server.config.ts, frontend/yarn.lock
=> feat(sentry): added sentry

frontend/app/chat/[chatId]/page.tsx, frontend/app/chat/components/ChatMessages/index.tsx, frontend/app/chat/components/ChatsList/index.tsx, frontend/app/chat/layout.tsx, frontend/lib/components/NavBar/components/NavItems/components/BrainsDropDown.tsx
This PR -
- replaces `overflow-scroll` with `overflow-auto` in the `BrainsDropDown` and in chats list.
- `ChatsList`, `BrainsDropDown` and `ChatMessages` now use the custom scrollbar style defined in the `.scrollbar` css class
- use predefined components in `frontend/lib/components/ui`, namely `Field` and `Button` in the `BrainsDropDown` component instead of HTML primitives
- add enter and exit animations using `AnimatePresence` for `BrainsDropDown`
=> remove blank scrollbars and use predefined components

backend/llm/base.py
Building .llm to be a collection of LLM classes. 
[x] BaseBrainPicking
[ ] OpenAIBrainPicking (old brainpicking) WIP
[ ] OpenAIFunctionsBrainPicking  WIP
[ ] PrivateGPT4AllBrainPicking (old privatebrainpicking) WIP
=> feat: base class for llms

README.md
The license link in README points to a LICENSE.md file which doesn't exist anymore, but LICENSE does. Hence, updated the LICENSE link to point to the correct file.
=> Update LICENSE link in README

migration.sh
**Context:** I couldn't get Quiver running locally using `install_helper.sh`. After some troubleshooting, it turned out that I had used the anon key for Supabase in place of the secret key, and so my initial install attempt was unsuccessful. Even when I fixed the keys, however, the migration scripts continually failed. It turned out this was because the `.migration_info` file was created on the initial attempt, but it had empty values. When the script sourced these values, nothing worked, as one might expect. 
**Problem:** `migration.sh` only checks for the existence of `.migration_info`, not whether the values are actually populated.
**Solution:** add a flag to indicate whether to prompt for DB info `prompt_for_db_info=false`, which becomes `true` if `.migration_info` does not exist OR …
=> If .migration_info values are missing, prompt user for them

frontend/lib/components/ui/Modal.tsx, frontend/lib/components/ui/Popover.tsx
Closes: #573 
Updated the `z-index` for mobile views,
=> Fix: mobile can't click brain ico

frontend/lib/components/NavBar/components/NavItems/components/BrainsDropDown/components/AddBrainModal.tsx
- Close modal on brain creation
=> Close new brain modal after creation

README.md
Just a small edit to make for the main page to fix the link :)
Fix misspelled link (https://github.com/stangirard/quivr/graphs/ciontributors) to https://github.com/stangirard/quivr/graphs/contributors
=> Fix misspelled link to contributors page

backend/core/routes/chat_routes.py
Just updates `NullableUUID` to extend from `UUID`. This lets FastAPI infer the correct field schema and resolves the /docs and /redocs endpoint failing to render
Just updates `NullableUUID` to extend from `UUID`. This lets FastAPI infer the correct field schema and resolves the /docs and /redocs endpoint failing to render
=> fix(backend): FastAPI docs broken due to missing schema for `NullableUUID`

frontend/app/explore/DocumentItem/DocumentData.tsx, frontend/app/explore/DocumentItem/__tests__/DocumentData.test.tsx
React is unable to render an object as a React child. The component was iterating over a brain document's keys and values, and attempting to render the value. However, one of the document's keys, `brains_vectors`, is an array of objects, which is not a valid React child.
In this PR I check the value type before rendering, and skip rendering that value if it's defined and an object.
Closes https://github.com/StanGirard/quivr/issues/763.
Before | After
--- | ---
=> fix(frontend): correctly display document information in explore view details

frontend/lib/components/ui/Toast/components/Toast.tsx
=> Fix: Toast message hidden under the footer

backend/core/llm/base.py, backend/core/llm/openai.py, backend/core/llm/qa_base.py, backend/core/routes/chat_routes.py, backend/core/vectorstore/supabase.py, frontend/app/chat/[chatId]/hooks/useChat.ts, frontend/app/chat/[chatId]/hooks/useQuestion.ts, frontend/lib/context/BrainConfigProvider/types.ts
Implement streaming for QA retrieval
=> feat(chat): added streaming

backend/core/routes/chat_routes.py
Solves "TypeError: HTTPException() takes no keyword arguments"
EDIT: also fixed an error in the user id comparison (current_user.id is a UUID object, chat.user_id is a str)
Currently, when `PUT /chat/:chat_id/metadata` is called, the error "TypeError: HTTPException() takes no keyword arguments" is raised due to an incorrect import.
See also: https://stackoverflow.com/questions/73330113/typeerror-httpexception-takes-no-keyword-arguments
=> fix(chat routes): HTTPException import correction

backend/core/llm/qa_base.py, backend/core/models/chat.py, backend/core/models/chats.py, backend/core/models/databases/supabase/chats.py, backend/core/repository/brain/get_brain_prompt_id.py, backend/core/repository/chat/get_chat_history.py, backend/core/repository/chat/update_chat_history.py, backend/core/routes/chat_routes.py, scripts/20230809154300_add_prompt_id_brain_id_to_chat_history_table.sql, scripts/tables.sql
- Update chat_history table
- Update some entities and DTOs
- Update chat controller
=> feat(chatMessages): add brain_id and prompt_id columns 

backend/core/crawl/crawler.py, backend/core/requirements.txt
Used existing process code, added logic to recursevely navigate linked pages. Not limiting to be the same domain or subdomain. Depth is defined in environment variable CRAWL_DEPTH. Maybe it should be specified in documentation.
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented hard-to-understand areas
- [x ] I have ideally added tests that prove my fix is effective or that my feature works
- [x ] Any dependent changes have been merged
=> feat (926): make crawl recursively navigate linked pages

backend/core/llm/qa_base.py, backend/core/repository/brain/get_brain_prompt_id.py, backend/core/repository/brain/get_default_user_brain.py
- Fix chat question endpoint 500 error caused by https://github.com/StanGirard/quivr/pull/912
- Typo on `get_brain_prompt_id` logic
- Logging issue at `get_default_user_brain`
- Currently not returning the answer from the end point
Fixes #952
=> fix(chatMessages): Fix error on answering question

install_helper.sh
Upon running `./install_helper.sh`, `backend/.env` couldn't be found because it's not existant.
I fixed it by adding the `core` folder.
It's now `backend/core/.env`
=> Fixed backend .env file navigation

backend/core/routes/subscription_routes.py
First delete  the prompt related to the brain then the brain to avoid foreign key of prompt id error in brains table
=> fix(brain): delete brain with custom prompt

frontend/app/chat/[chatId]/components/ChatMessages/components/ChatMessage/components/ChatMessage.tsx, frontend/app/chat/[chatId]/page.tsx
Correcting tailwind assets, 
`overflow-scroll` will always show scroll even if there is no need for scroll changed that to `overflow-hidden` this will enable scroll if there is a need
Corrected the return to better view code.
Before:
After:
Before:
After:
=> feat(chat): revise scroll logic and improve code display

backend/core/Dockerfile
=> feat(docker): improved size image

backend/chat_service.py, backend/routes/chat_routes.py, backend/routes/crawl_routes.py, backend/routes/misc_routes.py, backend/routes/upload_routes.py
Added Health endpoint for uptime
=> feat(health): added endpoint for services

frontend/app/chat/components/ChatsList/components/ChatsListItem/ChatsListItem.tsx
- update hover color : blue for modifying and red for delete
- remove chat id from chat lists
=> feat: Remove chat id from chat list

frontend/app/explore/DocumentItem/index.tsx, frontend/app/invitation/[brainId]/hooks/useInvitation.ts, frontend/app/upload/components/Crawler/hooks/useCrawler.ts, frontend/app/upload/components/FileUploader/hooks/useFileUploader.ts, frontend/app/upload/page.tsx, frontend/lib/context/BrainProvider/hooks/useBrainProvider.ts, frontend/services/analytics/useEventTracking.ts, frontend/services/analytics/useJune.ts
Bug origin was missing "track" of june hook from dependencies
=> fix(analytics): june debug for real

.gitignore, backend/Dockerfile
Fixes https://github.com/StanGirard/quivr/issues/1030. Tested on both Windows and a Macbook M1 Pro. 
The error was fixed by installing and adding Rust to PATH, and `build-essential` to include the C compiler and other essential build tools, as they were needed to compile certain dependencies, including Rust-related ones.
=> fix(dockerfile): backend Dockerfile exit code 1

backend/chat_service.py, backend/crawl/crawler.py, backend/crawl_service.py, backend/llm/qa_base.py, backend/main.py, backend/models/brains.py, backend/models/files.py, backend/repository/brain/get_brain_for_user.py, backend/repository/brain/get_user_brains.py, backend/repository/brain/update_brain.py, backend/repository/chat/update_message_by_id.py, backend/repository/user_identity/create_user_identity.py, backend/repository/user_identity/update_user_properties.py, backend/routes/api_key_routes.py, backend/routes/chat_routes.py, backend/upload_service.py
The objective of this PR is to guarantee the successful execution of backend CI tests. Our current challenge involves a growing count of test failures. This is compounded by instances where a single test failure goes unnoticed, subsequently triggering more test failures down the line. To address this issue, we need to enhance our CI monitoring and maintenance practices. It's crucial to emphasize that, moving forward, any CI test failures are likely to be significant and indicative of underlying problems requiring resolution.
Furthermore, it's important to note that adding skip instructions directly to the codebase should be avoided. Such instructions can obscure genuine issues and prevent the identification of actual problems within the code.
=> test(backend): skip failing tests

backend/llm/qa_headless.py, backend/repository/chat/format_chat_history.py, backend/routes/chat_routes.py
Unskip `qa_headless.py` linter tests
https://github.com/StanGirard/quivr/assets/63923024/15c7d622-3814-46fd-b839-e174d5c6b9e2
=> test: unskip `qa_headless.py` linter tests

backend/models/databases/supabase/brains.py, backend/repository/brain/__init__.py, backend/repository/brain/get_question_context_from_brain.py, backend/routes/brain_routes.py
- Add endpoint for getting context to a question from brain.
- The endpoint can be used by 3rd party app that does not want to get LLM answer, but instead just want to get the vector store search result for a query.
- Example: RealChar using it here https://github.com/Shaunwei/RealChar/pull/406
=> feat(brain): add endpoint to return context to question

frontend/app/chat/[chatId]/__tests__/page.test.tsx, frontend/app/chat/[chatId]/hooks/useChat.ts, frontend/app/chat/components/ChatsList/components/NewChatButton.tsx
- When a user is on `/chat/xxx-xxx-xx-xxx` and clicks on the `New Chat` button, they are redirected to `/chat/`.
- However, when the user is on `/chat/` and then clicks on the `New Chat` button, nothing happens because the current page is already the destination page. To fix this, I reload the page in this case.
=> feat: handle new chat button click

frontend/lib/components/AddBrainModal/hooks/useAddBrainModal.ts, frontend/lib/components/ui/Toast/components/Toast.tsx
=> feat: add name missing error in new brain modal 

frontend/app/chat/components/ChatsList/index.tsx
Make chatlist scrollable
https://github.com/StanGirard/quivr/assets/63923024/955cc714-b5d2-45db-aae7-7bb5eb073fae
=> feat: make chatlist scrollable

frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/SettingsTab.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/useSettingsTab.ts, frontend/lib/components/AddBrainModal/AddBrainModal.tsx, frontend/lib/components/ui/Field.tsx
=> feat(newBrain): update data validation logic and add * on required fields

frontend/app/chat/[chatId]/components/ChatMessages/__tests__/ChatMessages.test.tsx, frontend/app/chat/[chatId]/components/ChatMessages/components/ChatMessage/components/ChatMessage/ChatMessage.tsx, frontend/app/chat/[chatId]/components/ChatMessages/components/ChatMessage/components/ChatMessage/components/QuestionBrain.tsx, frontend/app/chat/[chatId]/components/ChatMessages/components/ChatMessage/components/ChatMessage/components/QuestionPrompt.tsx, frontend/app/chat/[chatId]/components/ChatMessages/components/ChatMessage/components/ChatMessage/index.ts, frontend/app/chat/[chatId]/components/ChatMessages/components/ChatMessage/components/index.ts, frontend/app/chat/[chatId]/components/ChatMessages/components/ChatMessage/index.ts, frontend/app/chat/[chatId]/components/ChatMessages/components/index.ts, frontend/app/chat/[chatId]/components/ChatMessages/index.tsx
Handle prompt or brain name missing
https://github.com/StanGirard/quivr/assets/63923024/5e772010-477c-46bc-b8e8-ec94c92da220
=> feat(chatMessage): update attributes display

frontend/app/brains-management/[brainId]/components/BrainManagementTabs/hooks/useBrainManagementTabs.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/types.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/utils/getTargetedTab.ts, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatBar/components/MentionInput/components/SuggestionRow.tsx
- Redirect to brains settings people tab on share button click from chatbar
=> feat: change share brain button logic

frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/useSettingsTab.ts
- handle nullish value to prevent unnecessary validation while updating brain settings
=> fix(brainsSettings): handle nullish value from api call

frontend/app/App.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/useSettingsTab.ts, frontend/lib/api/brain/config.ts, frontend/lib/components/TrackingWrapper.tsx, frontend/package.json, frontend/yarn.lock
Before:
https://github.com/StanGirard/quivr/assets/63923024/9b5bf9bd-b071-45e9-883f-1e2065a3c322
After:
https://github.com/StanGirard/quivr/assets/63923024/92222655-a09b-4b37-a5f1-8a779083501c
To improve UX on first load, we can add a loader... WDYT @Chloeroumengas @danielcgilibert @lamiabnn ?
=> feat: add tanstack query and optimistic fetch on brains settings page

frontend/app/layout.tsx
- FeatureFlags have been added back to the context of the app
- Fixed vercel environment variables: wrong env key name NEXT_PUBLIC_GROWTHBOOK_CLIENT_KEY
=> 🚑 fix feature flags -> add it back to context

backend/llm/qa_base.py, backend/llm/qa_headless.py, backend/requirements.txt
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
Example:
docs on langchain integration https://python.langchain.com/docs/integrations/chat/litellm 
```python
ChatLiteLLM(model="gpt-3.5-turbo")
ChatLiteLLM(model="claude-2", temperature=0.3)
ChatLiteLLM(model="command-nightly")
ChatLiteLLM(model="replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1")
```
In addition LiteLLM client allows you to n [Experimental + Optional Features]:
* A/B test LLMs in production
* Dynamically control each LLMs prompt, temperature, top_k etc in our UI (no need to re-deploy code)
* Logging to view input/outputs for each LLM
Here's a link to a live demo of litellm client: https://admin.litellm.ai/ 
Please include a …
=> feat(liteLLM): Add support for Azure OpenAI, Palm, Claude-2, Llama2, CodeLlama (100+LLMs) 

frontend/next.config.js
Fix csp headers in prod by adding growthbook url to connect-src 
=> fix(csp): add growthbook to csp headers

backend/models/databases/repository.py, backend/models/databases/supabase/__init__.py, backend/models/databases/supabase/notifications.py, backend/models/databases/supabase/supabase.py, backend/models/notifications.py, backend/repository/notification/add_notification.py, backend/repository/notification/update_notification.py, backend/routes/crawl_routes.py, backend/routes/upload_routes.py, scripts/20230906151400_add_notifications_table.sql, scripts/tables.sql
- Add notification table
- Create notification at the beginning of an upload and a crawl
- Update notification at the end of upload or crawl pocess
=> feat: add notifications table, and push notification on upload and crawl

backend/routes/crawl_routes.py, backend/routes/upload_routes.py, frontend/lib/api/crawl/crawl.ts, frontend/lib/api/upload/upload.ts
- updae crawl and upload endpoints
=> fix: update crawl and upload endpoints

.gitignore, README.md, docs/docs/get_started/intro.md, install_helper.sh
By not specifying `-f docker-compose.yml` in the docker compose command, it allows more flexible use of configuration files. `docker-compose.yml` is already the default config file when none is specified, and this also allows overrides via `docker-compose.override.yml`, which is recognized by default.
=> make docker compose command more flexible

backend/main.py, backend/routes/notification_routes.py, frontend/app/chat/[chatId]/components/ActionsBar/ActionsBar.tsx, frontend/app/chat/[chatId]/components/ActionsBar/hooks/useActionBar.ts, frontend/app/chat/[chatId]/components/ActionsBar/hooks/useKnowledgeUploader.ts, frontend/app/chat/[chatId]/hooks/useSelectedChatPage.ts, frontend/app/chat/[chatId]/utils/getChatNotificationsQueryKey.ts, frontend/app/chat/components/ChatsList/__tests__/ChatsList.test.tsx, frontend/lib/api/notification/__tests__/useNotificationApi.test.ts, frontend/lib/api/notification/notification.ts, frontend/lib/api/notification/useNotificationApi.ts
- Add polling logic on pending notifications on chat page
https://github.com/StanGirard/quivr/assets/63923024/188bd89f-6007-443f-bc5f-7ed1466ae3f8
=> feat: add polling for pending notifications

backend/models/brains.py, backend/models/databases/supabase/user_usage.py, backend/models/settings.py, backend/models/user_usage.py, backend/routes/brain_routes.py, backend/routes/chat_routes.py, backend/routes/crawl_routes.py, backend/routes/upload_routes.py, backend/routes/user_routes.py, docker-compose.yml, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/SettingsTab.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/useSettingsTab.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/utils/getAccessibleModels.ts, frontend/app/chat/[chatId]/__tests__/page.test.tsx, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ConfigModal/ConfigModal.tsx, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ConfigModal/hooks/useConfigModal.ts, frontend/app/user/components/ApiKeyConfig/hooks/__tests__/useApiKeyConfig.test.ts, frontend/app/user/components/ApiKeyConfig/hooks/useApiKeyConfig.ts, frontend/app/user/page.tsx, frontend/lib/api/user/__tests__/useUserApi.test.ts, frontend/lib/api/user/config.ts, frontend/lib/api/user/useUserApi.ts, frontend/lib/api/user/user.ts, frontend/lib/helpers/getAccessibleModels.ts, frontend/lib/types/User.ts, scripts/202309127004032_add_user_limits.sql, scripts/tables.sql
https://github.com/StanGirard/quivr/assets/63923024/34d1e3c1-5267-4a5f-8c85-3d4166c64417
=> feat: the good user management

frontend/app/chat/[chatId]/components/ActionsBar/ActionsBar.tsx, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/FeedBrainInput/FeedBrainInput.tsx, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/FeedBrainInput/components/BrainSelector/BrainSelector.tsx, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/FeedBrainInput/components/BrainSelector/hooks/useBrainSelector.tsx, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/index.tsx, frontend/app/chat/[chatId]/components/ActionsBar/hooks/useKnowledgeUploader.ts
Submit upload on Enter : https://github.com/StanGirard/quivr/issues/1108
=> feat: submit upload on Enter

backend/routes/chat_routes.py, frontend/app/chat/[chatId]/hooks/useSelectedChatPage.ts
=> feat(notificatins): higher refresh rate

backend/models/databases/supabase/notifications.py
=> fix(notifications): greater than 5 minutes ago not less

.aws/task_definition.json, .aws/task_definition_preview.json, .aws/task_definition_preview_worker.json, .aws/task_definition_prod_worker.json, backend/celery_task.py
Decreased cpu to 256 to increase number
=> feat(aws): improved size

.aws/task_definition.json, .aws/task_definition_preview.json, .aws/task_definition_preview_worker.json, .aws/task_definition_prod_worker.json, backend/Dockerfile, backend/celery_worker.py, backend/models/databases/supabase/notifications.py
Added concurrency 4 for celery and 6 for backend
=> feat(concurrency): added concurrency for increased performance

backend/llm/qa_base.py, backend/llm/qa_headless.py
=> feat(prompt): improved answer readability with markdown and aerataed

frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/ChatNotification/components/NotificationDisplayer/NotificationDisplayer.tsx
=> fix(notification): information now displayed on the right

frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/QADisplay/components/MessageRow/MessageRow.tsx
=> feat(chat): added copy feature to message

backend/models/databases/supabase/chats.py, frontend/app/chat/components/ChatsList/components/ChatsListItem/ChatsListItem.tsx, frontend/app/chat/components/ChatsList/index.tsx, frontend/lib/utils.ts
Chats ordered & with Today, Yesterday, Last 7 days and more ;)
=> fix(chats): now in order and with a little bonus ;)

frontend/lib/api/brain/types.ts, frontend/lib/components/AddBrainModal/AddBrainModal.tsx, frontend/lib/components/AddBrainModal/components/PublicAccessConfirmationModal.tsx, frontend/lib/components/AddBrainModal/hooks/useAddBrainModal.ts, frontend/lib/components/AddBrainModal/styles.css, frontend/lib/components/ui/Modal.tsx, frontend/lib/components/ui/Radio.tsx, frontend/lib/config/defaultBrainConfig.ts, frontend/lib/types/brainConfig.ts, frontend/package.json, frontend/public/locales/en/brain.json, frontend/public/locales/es/brain.json, frontend/public/locales/fr/brain.json, frontend/public/locales/pt-br/brain.json, frontend/public/locales/ru/brain.json, frontend/public/locales/zh-cn/brain.json, frontend/yarn.lock
- add brain status input
- update translations
- add confirmation modal for brain status changing to public
https://github.com/StanGirard/quivr/assets/63923024/f8110f46-a2e7-4af4-b429-a55571848bee
https://github.com/StanGirard/quivr/issues/1206
=> feat: add public brain creation

backend/models/brain_entity.py, backend/models/databases/supabase/brains.py, backend/repository/brain/get_user_brains.py, backend/routes/brain_routes.py, frontend/app/brains-management/[brainId]/components/BrainListItem/BrainListItem.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/BrainManagementTabs.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/SettingsTab.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/useSettingsTab.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/hooks/useBrainManagementTabs.ts, frontend/lib/api/brain/utils/mapBackendMinimalBrainToMinimalBrain.ts, frontend/lib/components/ui/Chip.tsx, frontend/lib/config/LocaleConfig/resources.ts, frontend/lib/context/BrainProvider/types.ts, frontend/shared/SaveButton.tsx
https://github.com/StanGirard/quivr/assets/63923024/a7e2cf5c-4974-40fe-a2e3-667b88df59a4
https://github.com/StanGirard/quivr/issues/1207
=> feat: display brain status on settings page

backend/models/brain_entity.py, backend/models/databases/supabase/brains.py, backend/repository/brain/create_brain.py, backend/repository/brain/get_public_brains.py, backend/routes/brain_routes.py, frontend/app/brains-management/[brainId]/components/BrainListItem/BrainListItem.tsx, frontend/app/brains-management/[brainId]/components/BrainsList.tsx, frontend/app/brains-management/[brainId]/hooks/useBrainsList.ts, frontend/app/brains-management/library/components/PublicBrainItem.tsx, frontend/app/brains-management/library/hooks/useBrainsLibrary.tsx, frontend/app/brains-management/library/page.tsx, frontend/lib/api/brain/__tests__/useBrainApi.test.ts, frontend/lib/api/brain/brain.ts, frontend/lib/api/brain/config.ts, frontend/lib/api/brain/useBrainApi.ts, frontend/lib/components/AddBrainModal/AddBrainModal.tsx, frontend/lib/components/ui/Field.tsx, frontend/lib/context/BrainProvider/types.ts, frontend/public/locales/en/brain.json, frontend/public/locales/es/brain.json, frontend/public/locales/fr/brain.json, frontend/public/locales/pt-br/brain.json, frontend/public/locales/ru/brain.json, frontend/public/locales/zh-cn/brain.json
- Add `/GET brains/public` route
- Add new DTO PublicBrain
- Add brain library page layout
- Update SDK
https://github.com/StanGirard/quivr/assets/63923024/6dde4730-0bea-4e8d-a116-8f264bcb7b8a
=> feat: add public brain page

backend/models/brain_entity.py, backend/models/databases/supabase/brains.py, backend/repository/brain/create_brain.py, backend/repository/brain/get_public_brains.py, backend/routes/brain_routes.py, frontend/app/brains-management/[brainId]/components/BrainListItem/BrainListItem.tsx, frontend/app/brains-management/[brainId]/components/BrainsList.tsx, frontend/app/brains-management/[brainId]/hooks/useBrainsList.ts, frontend/app/brains-management/library/components/PublicBrainItem.tsx, frontend/app/brains-management/library/hooks/useBrainsLibrary.tsx, frontend/app/brains-management/library/page.tsx, frontend/lib/api/brain/__tests__/useBrainApi.test.ts, frontend/lib/api/brain/brain.ts, frontend/lib/api/brain/config.ts, frontend/lib/api/brain/useBrainApi.ts, frontend/lib/components/AddBrainModal/AddBrainModal.tsx, frontend/lib/components/ui/Field.tsx, frontend/lib/context/BrainProvider/types.ts, frontend/public/locales/en/brain.json, frontend/public/locales/es/brain.json, frontend/public/locales/fr/brain.json, frontend/public/locales/pt-br/brain.json, frontend/public/locales/ru/brain.json, frontend/public/locales/zh-cn/brain.json
- count brain number of subscribers
https://github.com/StanGirard/quivr/issues/1209
=> feat: count public brains number of subscribers

frontend/app/chat/components/ChatsList/components/ChatsListItem/components/UserButton.tsx, frontend/app/chat/components/ChatsList/components/ChatsListItem/hooks/useGravatar.ts, frontend/next.config.js
If the user already has a gravatar corresponding to her email :
Otherwise, the default :
=> feat: 👤 Implement gravatar

frontend/next.config.js
Add gravatar.com to the content security policy, so that it doesn't get blocked in production.
=> fix: 🔒️ add gravatar.com to the content security policy

frontend/app/chat/[chatId]/components/ActionsBar/components/KnowledgeToFeed/KnowledgeToFeed.tsx, frontend/app/chat/components/ChatsList/components/ChatsListItem/components/BrainManagementButton.tsx, frontend/e2e/index.ts, frontend/e2e/tests/createBrain.ts, frontend/e2e/tests/upload.ts, frontend/e2e/utils/login.ts, frontend/lib/components/KnowledgeToFeedInput/KnowledgeToFeedInput.tsx, frontend/lib/components/KnowledgeToFeedInput/components/Crawler/index.tsx, frontend/lib/components/NavBar/components/Logo.tsx, frontend/playwright.config.ts, frontend/public/locales/en/brain.json, frontend/public/locales/es/brain.json, frontend/public/locales/fr/brain.json, frontend/public/locales/pt-br/brain.json, frontend/public/locales/ru/brain.json, frontend/public/locales/zh-cn/brain.json
=> test: add e2e for crawling

frontend/app/App.tsx
When a user is logged out, it will try to fetch data and throw uncaught authentication errors in the console. This fix will only fetch if a user session exists.
=> fix: prevent fetch when user is not logged in

frontend/lib/components/ui/Select.tsx
React prefers camelCase for `svg` attributes. There was a `console.warning` being thrown in the `Select.tsx` component.
=> fix(Select): fix JSX typo

frontend/lib/components/Sidebar/Sidebar.tsx
Fixes the issue where the sidebar footer is not visible if the content is too long (like a too large chat history).
Before (we cannot see the footer) :
After (we can see it and scroll through the content):
=> fix: 🐛 Sidebar content should not hide the sidebar footer

frontend/next.config.js
Improve developper experience with CSP by turning the csp into object instead of a large string.
```ts
import { describe, expect } from "vitest";
process.env.NEXT_PUBLIC_SUPABASE_URL = "XXX";
process.env.NEXT_PUBLIC_BACKEND_URL = "YYY";
const OldContentSecurityPolicy =
`default-src 'self' https://fonts.googleapis.com ${process.env.NEXT_PUBLIC_SUPABASE_URL} https://api.june.so https://www.quivr.app/;
connect-src 'self' ${process.env.NEXT_PUBLIC_SUPABASE_URL} ${process.env.NEXT_PUBLIC_BACKEND_URL} https://api.june.so https://api.openai.com https://cdn.growthbook.io https://vitals.vercel-insights.com/v1/vitals;
img-src 'self' https://www.gravatar.com data:;
media-src 'self' https://user-images.githubusercontent.com https://www.quivr.app/ https://quivr-cms.s3.eu-west-3.amazonaws.com; …
```
=> refactor: ♻️ ContentSecurityPolicy as an object

frontend/lib/components/Sidebar/components/SidebarFooter/components/UserButton.tsx
In nextjs version 13, the `layout` attribute is deprecated in the `Image`.
Hence we had the following warning:
```
Image with src "https://www.gravatar.com/avatar/hash?d=mp" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
```
The fill attribute is not deprecated and plays the same role. (see the doc for the current props of Image : https://nextjs.org/docs/pages/api-reference/components/image)
=> fix: replace next/image's layout deprecated attribute

frontend/app/chat/[chatId]/page.tsx, frontend/app/globals.css
Remove the outline when focusing on divs
#1317
=> fix: remove undesired outlines around divs

backend/models/databases/repository.py, backend/models/databases/supabase/__init__.py, backend/models/databases/supabase/onboarding.py, backend/models/databases/supabase/supabase.py, backend/models/onboarding.py, backend/repository/onboarding/get_user_onboarding.py, backend/repository/onboarding/udpate_user_onboarding.py, backend/routes/onboarding_routes.py, scripts/20231004150000_add_onboarding_table.sql, scripts/tables.sql
https://github.com/StanGirard/quivr/issues/1328
=> feat: add onboarding table

frontend/next.config.js
Enable CSP in all environments (local/preview/prod).
Relies on NEXT_PUBLIC_ENV env variable, which should be `'local'|'preview'|'prod'`
```
default-src 'self' https://fonts.googleapis.com https://xxx.supabase.co https://api.june.so https://www.quivr.app/; connect-src 'self' https://xxx.supabase.co http://localhost:5050 https://api.june.so https://api.openai.com https://cdn.growthbook.io https://vitals.vercel-insights.com/v1/vitals; img-src 'self' https://www.gravatar.com data:; media-src 'self' https://user-images.githubusercontent.com https://www.quivr.app/ https://quivr-cms.s3.eu-west-3.amazonaws.com; script-src 'unsafe-inline' 'unsafe-eval' https://va.vercel-scripts.com/ https://www.quivr.app/ https://www.google-analytics.com/; frame-ancestors 'none'; style-src 'unsafe-inline' …
```
=> feat: enable CSP in all environments (local/preview/prod)

backend/routes/chat_routes.py
=> fix(question): fixed with user_settings

scripts/tables.sql
A missing ; in the CREATE query for onboarding tables breaks the script execution on Supabase.
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] Any dependent changes have been merged
=> FIX tables.sql - missing ; breaks SQL queries.

frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/__tests__/ChatDialogue.test.tsx, frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/index.tsx, frontend/app/chat/components/ChatsList/components/ChatsListItem/ChatsListItem.tsx, frontend/app/chat/components/ChatsList/components/WelcomeChat.tsx, frontend/app/chat/components/ChatsList/index.tsx, frontend/lib/api/onboarding/__test__/useOnboarding.test.ts, frontend/lib/api/onboarding/config.ts, frontend/lib/api/onboarding/onboarding.ts, frontend/lib/api/onboarding/useOnboardingApi.ts, frontend/lib/hooks/useOnboarding.ts, frontend/lib/types/Onboarding.ts, frontend/public/locales/en/chat.json, frontend/public/locales/es/chat.json, frontend/public/locales/fr/chat.json, frontend/public/locales/pt-br/chat.json, frontend/public/locales/ru/chat.json, frontend/public/locales/zh-cn/chat.json
https://github.com/StanGirard/quivr/issues/1361
https://github.com/StanGirard/quivr/assets/63923024/cc4b1c0a-363a-49f3-8306-181151554b34
=> feat: add Welcome chat

backend/models/databases/repository.py, backend/models/databases/supabase/onboarding.py, backend/repository/onboarding/update_user_onboarding.py, backend/routes/onboarding_routes.py, frontend/lib/hooks/useOnboarding.ts
https://github.com/StanGirard/quivr/issues/1384
https://github.com/StanGirard/quivr/assets/63923024/ac05456d-2817-4196-8afc-51b34a4d8c5f
=> feat: remove user onboarding on complete

frontend/app/(home)/components/Sections/DemoSection/DemoSection.tsx, frontend/lib/api/cms/config.ts, frontend/lib/api/cms/demoVideo.ts, frontend/lib/api/cms/useCmsApi.ts
Issue: https://github.com/StanGirard/quivr/issues/1460
=> feat: fetch demo video from CMS

frontend/app/brains-management/[brainId]/components/BrainsList/BrainsList.tsx, frontend/app/chat/components/ChatsList/index.tsx, frontend/app/user/page.tsx, frontend/lib/components/Sidebar/components/SidebarFooter/SidebarFooter.tsx, frontend/lib/components/Sidebar/components/SidebarFooter/components/BrainManagementButton.tsx, frontend/lib/components/Sidebar/components/SidebarFooter/components/SidebarFooterButton.tsx, frontend/lib/components/Sidebar/components/SidebarFooter/components/UpgradeToPlus.tsx, frontend/lib/components/Sidebar/components/SidebarFooter/components/UserButton.tsx, frontend/lib/components/Sidebar/components/SidebarFooter/styles/SidebarLinkStyle.tsx, frontend/lib/components/ui/Avatar.tsx
Epic: #1429
User Story: #1431
- Add an upgrade button in user settings.
- Remove hover links on sidebar buttons (otherwise the link could partially hide the button)
=> feat: upgrade button in user settings

frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/index.tsx, frontend/app/chat/[chatId]/components/ChatDialogueArea/ChatDialogue.tsx, frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/Onboarding/Onboarding.tsx, frontend/lib/hooks/useOnboarding.ts
=> feat: remove onboarding's feature flag

backend/auth/api_key_handler.py, backend/chat_service.py, backend/crawl_service.py, backend/main.py, backend/upload_service.py, backend/utils/__init__.py, backend/utils/handle_request_validation_error.py
=> refactor: fix bad smells

backend/routes/chat/brainful_chat.py, backend/routes/chat/brainless_chat.py, backend/routes/chat/factory.py, backend/routes/chat/interface.py, backend/routes/chat/utils.py, backend/routes/chat_routes.py
=> refactor:  chat_routes 

backend/llm/qa_headless.py, backend/routes/chat_routes.py, frontend/lib/helpers/defineMaxTokens.ts
=> feat: 🎸 max-token

frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/useSettingsTab.ts
=> fix: prompt update in brains management settings tab

backend/routes/brain_routes.py, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/SettingsTab.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/components/Prompt/Prompt.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/usePrompt.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/useSettingsTab.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/utils/checkBrainName.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/utils/checkOpenAiKey.ts
- Refactor useSettingsTab by extracting usePrompt and methods in utils
- Fix bug #1545 
=> refactor: extract prompt from settings

backend/loaders/telegram.py, backend/parsers/telegram.py, backend/repository/brain/get_question_context_from_brain.py, backend/utils/processors.py, backend/utils/vectors.py, backend/vectorstore/supabase.py, frontend/lib/helpers/acceptedFormats.ts, frontend/lib/helpers/getFileIcon.tsx, frontend/lib/types/SupportedFileExtensions.ts
added loaders and compatibility
=> feat: 🎸 telegram

frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/components/PublicPrompts/components/PublicPromptsList/PublicPromptsList.tsx
In https://www.quivr.app/brains-management, the Custom Prompt dropdown is partially covered by the cu
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
- [ X] I have commented hard-to-understand areas
- [ X] I have ideally added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged
=> style(prompts): update public prompts dropdown styling

frontend/app/(home)/components/HomeHeader/components/PopoverMenuMobile.tsx, frontend/lib/components/ui/Button.tsx
Issue: https://github.com/StanGirard/quivr/issues/1498
=> fix: fix button bad children error

migration.sh
In issue #1290 folks report difficulty running migrations on an existing instance. The current migration table includes a `name` column, but no `id` column:
```
CREATE TABLE IF NOT EXISTS migrations (
name VARCHAR(255)  PRIMARY KEY,
executed_at TIMESTAMPTZ DEFAULT current_timestamp
);
```
By changing the `migrations.sh` script to use the `name` field, the migrations run as expected.
=> Fix #1290 issue running migrations

docker-compose.dev.yml
When developing locally, I am reluctant to start containers with the `restart: always` option. I find they stick around longer than I want them to. In my opinion, `restart: unless-stopped` is a nice middle ground.
=> Use 'unless-stopped' instead of 'always' for development

backend/llm/qa_base.py, frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/QADisplay/components/MessageRow/MessageRow.tsx, frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/QADisplay/components/MessageRow/components/SourcesButton.tsx
added sources in front and backend
=> feat: 🎸 sources

frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/components/GeneralInformation/GeneralInformation.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/components/ModelSelection/ModelSelection.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/useSettingsTab.ts, frontend/lib/context/BrainProvider/types.ts
Issue: https://github.com/StanGirard/quivr/issues/1550
https://github.com/StanGirard/quivr/assets/63923024/f58e1ecb-635b-4d65-a6d9-288b0842a3ae
=> fix: allow to change model bro brain settings tab

docs/docs/Developers/contribution/_category_.json, docs/docs/Developers/contribution/install.md, docs/docs/Developers/selfHosted/Authentication.md, docs/docs/Developers/selfHosted/_category_.json, docs/docs/Developers/selfHosted/run_fully_local.md, docs/docs/Developers/selfHosted/vps_install.md
issue: https://github.com/StanGirard/quivr/issues/1580
=> docs: add auth modes config

backend/models/databases/repository.py, backend/models/databases/supabase/knowledge.py, backend/repository/knowledge/remove_brain_all_knowledge.py, backend/routes/knowledge_routes.py, backend/routes/subscription_routes.py, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/SettingsTab/hooks/usePrompt.ts
Issue: https://github.com/StanGirard/quivr/issues/1362
Demo:
https://github.com/StanGirard/quivr/assets/63923024/aa5e41f8-a738-41f2-b037-975788ad8611
=> fix: allow users to delete brains

backend/llm/qa_base.py
=> feat: 🎸 source documents

backend/models/ApiBrainDefinition.py, backend/models/databases/repository.py, backend/models/databases/supabase/__init__.py, backend/models/databases/supabase/api_brain_definition.py, backend/models/databases/supabase/onboarding.py, backend/models/databases/supabase/supabase.py, backend/repository/api_brain_definition/add_api_brain_definition.py, backend/repository/api_brain_definition/delete_api_brain_definition.py, backend/repository/api_brain_definition/get_api_brain_definition.py, scripts/2023110607100000_add_api_brain_definition_table.sql, scripts/tables.sql
Issue: https://github.com/StanGirard/quivr/issues/1549
=> feat: add api_brain_definition table

backend/models/brain_entity.py, backend/models/databases/supabase/brains.py, scripts/20231106110000_add_field_brain_type_to_brain_table.sql, scripts/tables.sql
Issue: https://github.com/StanGirard/quivr/pull/1601
Demo:
https://github.com/StanGirard/quivr/assets/63923024/a7fe76a7-8809-4ec7-b1e6-d6fe36928a5c
=> feat: add brain_type column to brain table

backend/llm/api_brain_qa.py, backend/llm/utils/call_brain_api.py, backend/llm/utils/extract_brain_api_params_values_from_llm_output.py, backend/llm/utils/get_api_brain_definition_as_json_schema.py, backend/llm/utils/make_api_request.py, backend/models/ApiBrainDefinition.py, backend/repository/external_api_secret/create_secret.py, backend/repository/external_api_secret/delete_secret.py, backend/repository/external_api_secret/read_secret.py, backend/routes/chat/brainful_chat.py, backend/routes/chat/brainless_chat.py, backend/routes/chat_routes.py
Issue: https://github.com/StanGirard/quivr/issues/1566
=> feat: add APIBrainQA 

backend/Dockerfile, frontend/Dockerfile
Currently, the production Docker images are very large, sitting at 4.17 GB for the frontend image, and 3.49 GB for backend images. This change adds multi-stage builds, to optimize the image sizes, which results in the following improvements:
- frontend image size: 4.17 GB -> 1.64 GB
- backend image size: 3.49 GB -> 1.71 GB
I hope this is appropriate as there is no open issue for this that I know of.
I implemented this change and tested it locally, and would be glad to discuss this and open an issue if necessary.
Image sizes before:
Image sizes after:
=> feat(docker): use multi-stage Docker builds for smaller images

backend/modules/user/repository/__init__.py, backend/modules/user/repository/get_user_email_by_user_id.py, backend/modules/user/repository/get_user_identity.py, backend/modules/user/service/__init__.py, backend/routes/subscription_routes.py, frontend/public/locales/en/chat.json, scripts/20231116102600_add_get_user_email_by_user_id.sql, scripts/tables.sql
Fix subscription routes on get users
Revert changes deleting the function to get user email from its id in SQL
https://www.loom.com/share/46534965a83f4296898495ac370b3451?sid=7f582838-32f6-4812-960e-c80d71517a6d
=> fix: delete brain on users click in brains management

backend/routes/brain_routes.py, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/BrainManagementTabs.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/KnowledgeTab/index.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/NoAccess.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/PeopleTab/PeopleTab.tsx, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/hooks/useBrainFetcher.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/hooks/useBrainManagementTabs.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/utils/getBrainPermissions.ts, frontend/app/brains-management/[brainId]/components/BrainManagementTabs/utils/isUserBrainEditor.ts, frontend/lib/hooks/useShareBrain.ts
- Fixes the following issues: 
- When I acces a brain shared with me as viewer, I should be able to fetch the brain settings from the BE
- When I access a public brain, if im not owner or editor I should not be able to see the tabs "People" nor "Knowledge"
- When I access a private brain, if im not owner or editor I should be able to see the tabs "People" or "Knowledge" with a no access - resquest access from owner message
=> fix: brain management shared brain access

.gitignore, Makefile, backend/.dockerignore, backend/Dockerfile.dev, backend/main.py, backend/requirements.txt, docker-compose.dev.yml, docker-compose.yml, frontend/Dockerfile
=> feat: 🎸 docker reduced size by 2

backend/llm/api_brain_qa.py, backend/llm/utils/make_api_request.py
=> fix: 🐛 api

backend/routes/knowledge_routes.py
```
======================================================================
backend-core  | --- Logging error ---
backend-core  | Traceback (most recent call last):
backend-core  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
backend-core  |     msg = self.format(record)
backend-core  |           ^^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
backend-core  |     return fmt.format(record)
backend-core  |            ^^^^^^^^^^^^^^^^^^
backend-core  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
backend-core  |     record.message = record.getMessage()
backend-core  |                      ^^^^^^^^^^^^^^^^^^^
backend-core  |   File …
```
=> Fixes string formatting when logging knowledge table

backend/llm/api_brain_qa.py, backend/routes/chat_routes.py
Issue: https://github.com/StanGirard/quivr/issues/1690
=> fix: update max token overwrite logic

frontend/app/brains-management/library/components/PublicBrainItem/components/SecretsDefinitionFields.tsx, frontend/app/brains-management/library/components/PublicBrainItem/hooks/usePublicBrainItem.ts
Demo: 
https://github.com/StanGirard/quivr/assets/63923024/c0511a45-05fc-4059-9b0c-9f2f4b7ee12a
Issue:
https://github.com/StanGirard/quivr/issues/1713
=> fix: update public brain subscription logic

backend/models/databases/supabase/brains.py, backend/routes/knowledge_routes.py
Issue: https://github.com/StanGirard/quivr/issues/1724
=> feat: improve delete knowledge performance

scripts/tables.sql
now increased deault limit and added gpt-4
=> feat: 🎸 local user

.backend_env.example, backend/llm/api_brain_qa.py, backend/llm/qa_base.py, backend/llm/qa_headless.py, backend/models/settings.py, backend/requirements.txt, docs/docs/Developers/selfHosted/run_fully_local.md, frontend/sentry.client.config.ts, frontend/sentry.edge.config.ts, frontend/sentry.server.config.ts
=> feat: implement local llms

frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/components/Editor/hooks/useMentionConfig.ts, frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/QADisplay/components/MessageRow/MessageRow.tsx
Issue: https://github.com/StanGirard/quivr/issues/1762
Demo: 
https://github.com/StanGirard/quivr/assets/63923024/c578b9f0-5b1d-4196-85cf-042a93acd9c6
=> fix: update mention suggestion filtering logic

frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/components/Editor/hooks/useCreateEditorState.ts, frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/QADisplay/components/MessageRow/components/SourcesButton.tsx
Issue: https://github.com/StanGirard/quivr/issues/1774
=> feat: track response source usage

README.md
There is a missing setup instruction in the README for MacOS users.
If the filesystem is not set to VirtioFS in Docker Desktop, a SupaBase error is triggered:
`The file system does not support extended attributes or has the feature disabled` 
Supabase related issue: https://github.com/orgs/supabase/discussions/9539
=> doc: add VirtioFS instruction for MacOS users

frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/QADisplay/components/MessageRow/components/MessageContent.tsx
Text color was being overridden.
Removed `text-gray-800` in MessageContent.tsx.
Before:
After:
=> fix: text not clear in dark mode

frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/components/Editor/components/MentionsList/MentionsList.tsx, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/components/Editor/components/MentionsList/hooks/useSuggestionsOverflowHandler.ts, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/components/Editor/hooks/useMentionConfig.ts
Issue: https://github.com/StanGirard/quivr/issues/1835
Demo:
https://github.com/StanGirard/quivr/assets/63923024/efd0795e-dd4a-45d6-bc53-56f630e94cb6
=> feat: add brains list overflow indicator

docker-compose-ollama.yml
I tried to use the Quivr with the docker-compose-ollama.yml option but the docker compose build crashed with the following messages:
`{"code":"58P01","details":null,"hint":null,"message":"could not access file \"$libdir/wrappers-0.1.19\": No such file or directory"}`
After a quick search I saw that the issue was related to the supabase/postgres image and after a quick compare with the default docker-compose.yml i saw that it uses a newer version for the supabase/postgres image and when i tried the newer version with the docker-compose-ollama.yml the errors stopped and the app works fine.
Relative issues: #1846 #1822 #1850
=> fix(ollama): - update supabase-db postgres docker image version

backend/llm/api_brain_qa.py, backend/llm/knowledge_brain_qa.py, backend/llm/qa_headless.py, backend/llm/qa_interface.py, backend/llm/rags/quivr_rag.py, backend/llm/rags/rag_interface.py
- Add `QAInterface` which should be implemented by all custom answer generator to be compatible with Quivr
- Add `RAGInterface` which should be implemented by all RAG classes
=> feat: add custom rag first abstraction layer

backend/repository/brain/get_question_context_from_brain.py, backend/repository/files/generate_file_signed_url.py
=> feat: Add file URL to DocumentAnswer objects

frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ActionsModal/components/FeedCardTrigger/hooks/useFeedCardTrigger.ts
Demo: 
https://github.com/StanGirard/quivr/assets/63923024/c25e5892-be59-47ed-b1ea-8ce6bcc50214
=> feat: add default feed button label

backend/llm/api_brain_qa.py, backend/llm/composite_brain_qa.py, backend/llm/knowledge_brain_qa.py, backend/llm/qa_headless.py, backend/llm/qa_interface.py, backend/modules/brain/service/brain_service.py, backend/modules/chat/controller/chat/brainful_chat.py, backend/modules/chat/controller/chat_routes.py, backend/modules/chat/dto/outputs.py
- generate_stream, generate and save answer in BE
-  Create an intermediary make_streaming_recursive_tool_calls async function 
- Save intermediary answers in new message logs column then fetch and display in front
=> feat: chat with compositeBrain ( with/out streaming)

frontend/app/App.tsx, vercel.json
=> feat: 🎸 posthog

supabase/config.toml, supabase/migrations/20240107231636_policies.sql, supabase/seed.sql
added Row level security on postgres
=> feat: 🎸 policies

frontend/lib/types/BrainConfig.ts, frontend/lib/types/Testimonial.ts
=> fix(frontend): uniformize case for types

frontend/app/brains-management/[brainId]/components/BrainManagementTabs/components/PeopleTab/PeopleTab.tsx, frontend/lib/components/UserToInvite.tsx
=> fix: 🐛 subscription

frontend/app/brains-management/page.tsx, frontend/app/chat/[chatId]/components/DataPanel/DataPanel.module.scss, frontend/app/chat/[chatId]/components/DataPanel/DataPanel.tsx, frontend/app/chat/[chatId]/components/DataPanel/components/RelatedBrains/RelatedBrains.module.scss, frontend/app/chat/[chatId]/components/DataPanel/components/RelatedBrains/RelatedBrains.tsx, frontend/app/chat/[chatId]/hooks/useChat.ts, frontend/app/chat/[chatId]/page.module.scss, frontend/app/chat/[chatId]/page.tsx, frontend/app/chat/[chatId]/types/index.ts, frontend/app/search/page.module.scss, frontend/lib/components/Menu/Menu.tsx, frontend/lib/components/Menu/components/AnimationDiv.tsx, frontend/lib/components/ui/FoldableSection/FoldableSection.module.scss, frontend/lib/components/ui/FoldableSection/FoldableSection.tsx, frontend/lib/components/ui/Icon/Icon.module.scss, frontend/lib/components/ui/Icon/Icon.tsx, frontend/lib/components/ui/SearchBar/SearchBar.module.scss, frontend/lib/components/ui/TextButton/TextButton.module.scss, frontend/lib/helpers/iconList.ts, frontend/lib/types/MessageMetadata.ts, frontend/styles/_Colors.module.scss
=> feat(panel): added

frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/components/Editor/Editor.tsx
=> fix(frontend): clear message input on submit

backend/llm/api_brain_qa.py, backend/modules/brain/dto/inputs.py, backend/modules/chat/controller/chat/brainful_chat.py, backend/modules/chat/service/chat_service.py
=> fix: 🐛 related

docs/developers/contribution/guidelines.mdx
To better see when there are missing translations or contribution opportunities.
- Added a dynamic image for markdown that renders the translation status
=> feat: Added translation status badge from inlang

frontend/.eslintrc.js, frontend/app/chat/[chatId]/components/DataPanel/components/RelatedBrains/RelatedBrains.tsx, frontend/app/chat/[chatId]/page.module.scss, frontend/app/chat/[chatId]/types/index.ts
- Select current Brain from brain_id instead of brain_name
- Avoid multiple calls of useEffect
=> fix(frontend): clean related Brains useEffect

frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/components/Editor/components/MentionsList/MentionsList.tsx, frontend/lib/components/SearchModal/SearchModal.module.scss, frontend/lib/components/SearchModal/SearchModal.tsx
=> fix(frontend): click on mention list on search bar in modal bug

frontend/public/locales/en/brain.json, frontend/public/locales/fr/brain.json
Typo in UI when creating new brain: "Ressources" ==> "Resources"
- [ X ] I have performed a self-review of my code
=> Fix typo of UI: Ressources ==> Resources

backend/modules/notification/repository/notifications.py, backend/modules/notification/service/notification_service.py, backend/modules/upload/controller/upload_routes.py, backend/repository/files/upload_file.py
now you can download & view pdf
=> fix: 🐛 upload

frontend/app/chat/[chatId]/components/DataPanel/DataPanel.tsx
=> fix(frontend): no sources repetition in data panel

backend/modules/prompt/tests/test_prompt.py
=> tests: Add tests for deleting prompts by ID

backend/celery_config.py
This pull request adds Redis configuration to the `celery_config.py` file. The `CELERY_BROKER_URL` has been replaced with `REDIS_HOST`, `REDIS_PORT`, and `REDIS_PASS` environment variables to configure the Redis broker and backend. This change allows for better integration with Redis in the application.
=> Add Redis configuration to celery_config.py

frontend/lib/api/brain/brain.ts
This pull request fixes the API endpoint for getting integration brains. Previously, the endpoint was missing a trailing slash, causing the request to fail. This PR adds the missing slash to the endpoint, ensuring that the request is successful.
=> Fix: API endpoint for getting integration brains

backend/repository/brain_subscription/resend_invitation_email.py, backend/routes/subscription_routes.py
This pull request fixes the `get_brain_details` API by adding a `user_id` parameter. Previously, the API did not include the `user_id` parameter, which caused issues when retrieving brain details. This fix ensures that the `user_id` is passed correctly to the API, allowing for accurate retrieval of brain details.
=> fix: get_brain_details API to include user_id parameter

backend/main.py, frontend/sentry.client.config.ts
This pull request reduces the sampling rate for Sentry traces to 0.1. This change ensures that only a small percentage of traces are captured, which helps to reduce the impact on performance and storage.
=> Reduce sampling rate for Sentry traces

backend/modules/brain/knowledge_brain_qa.py
This pull request adds the `max_input` and `max_tokens` parameters to the `KnowledgeBrainQA` constructor. These parameters allow for setting the maximum input length and maximum number of tokens for the KnowledgeBrainQA model. This provides more flexibility and control over the input size and tokenization process.
=> Add max_input and max_tokens parameters to KnowledgeBrainQA constructor

docs/developers/contribution/llm/ollama.mdx
https://github.com/QuivrHQ/quivr/blob/38de2e744049eea8c6cf85e4f5e9572c21083591/docs/developers/contribution/llm/ollama.mdx#L20-L25
Due to architectural changes in the file system, the ollama documentation is out of date.
The sql files are now nested inside a `migrations` directory instead of at the root of the supabase directory.
Fixed by adding `migrations` to the path 
```bash
mv supabase/migrations/local_20240107152745_ollama.sql supabase/migrations/20240107152745_ollama.sql
supabase db reset
```
=> fix: ollama migration documentation

frontend/.gitignore, frontend/app/global-error.jsx, frontend/next.config.js, frontend/package.json, frontend/pages/_error.jsx, frontend/sentry.client.config.ts, frontend/sentry.edge.config.ts, frontend/sentry.server.config.ts, frontend/yarn.lock
This pull request updates the Sentry configuration file and adds a new ignore file. The changes include:
- Updating the `SENTRY_DSN` environment variable to `NEXT_PUBLIC_SENTRY_DSN`
- Updating the `@sentry/nextjs` package to version `7.102.1`
- Adding a new ignore file `.sentryclirc`
=> Update Sentry configuration and ignore file

frontend/sentry.client.config.ts, frontend/sentry.edge.config.ts, frontend/sentry.server.config.ts
Update the Sentry DSN environment variable to use the correct name. This ensures that Sentry is properly initialized when the DSN is set.
=> Fix Sentry DSN environment variable

frontend/.gitignore, frontend/sentry.client.config.ts, frontend/sentry.edge.config.ts, frontend/sentry.server.config.ts
This pull request updates the Sentry configuration to use the `NEXT_PUBLIC_SENTRY_DSN` environment variable instead of `SENTRY_DSN`. This ensures that the correct DSN is used for Sentry initialization.
=> fix: Update Sentry configuration to use NEXT_PUBLIC_SENTRY_DSN

backend/middlewares/cors.py, backend/repository/brain_subscription/resend_invitation_email.py, backend/supabase/functions/add-new-email/index.ts, frontend/app/(home)/page.tsx, frontend/next.config.js
This pull request updates the origins in cors.py, origin in resend_invitation_email.py, and referring_site in add-new-email/index.ts. It also refactors the code in home/page.tsx and next.config.js.
=> feat: new landing page

backend/modules/brain/integrations/Big/Brain.py, backend/modules/brain/integrations/SQL/Brain.py, backend/modules/brain/rags/quivr_rag.py
With this pull request, I add a fix that **enables Ollama**. 
Running quivr in a Docker container, Ollama needs to be accessed via http://host.docker.internal:11434.
This URL is defined as `api_base` of the `ChatLiteLLM` constructor. But there are calls that are missing `api_base`. This leads to fallback URLs being used. This is now fixed.
Fixes #2270 #2267 #2217 #2204 
None
=> fix(rag): add api_base

frontend/app/studio/[brainId]/BrainManagementTabs/components/SettingsTab/components/ModelSelection/ModelSelection.tsx, frontend/lib/components/ui/FieldHeader/FieldHeader.tsx
=> feat(frontend): add help tooltip for model selection

backend/modules/user/dto/inputs.py, backend/modules/user/entity/user_identity.py, backend/modules/user/repository/users.py, supabase/migrations/20240313024244_onboarding-user.sql
This pull request adds optional fields to the UserIdentity and UserUpdatableProperties classes in order to allow for more flexibility when updating user properties. The new fields include username, company, and onboarded. Additionally, the database schema has been updated to reflect these changes.
=> feat: Add optional fields to UserIdentity and UserUpdatableProperties

backend/modules/brain/integrations/Big/Brain.py, frontend/lib/helpers/defineMaxTokens.ts, frontend/lib/types/BrainConfig.ts
=> feat: mistral

supabase/migrations/20240320215813_fix_match_vector_function.sql
Fix match_vectors function that rank chunks in the wrong order 
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my code
- [ x ] I have commented hard-to-understand areas
=> fix(retriever): Update match_vectors sql function to rank chunks in correct order

backend/modules/ingestion/entity/ingestion.py
This pull request adds a new field, `url_required`, to the `IngestionEntity` class. This field is required for the ingestion process and will be used to store the URL of the entity.
=> feat: Add url_required field to IngestionEntity

backend/modules/assistant/controller/assistant_routes.py, backend/modules/assistant/dto/inputs.py, backend/modules/assistant/dto/outputs.py, backend/modules/assistant/ito/audio_transcript.py, backend/modules/assistant/ito/crawler.py, backend/modules/assistant/ito/ito.py, backend/modules/assistant/ito/summary.py
…dio_transcript and crawler assistants
=> feat: assistants

backend/modules/assistant/dto/outputs.py, backend/modules/assistant/ito/audio_transcript.py, backend/modules/assistant/ito/crawler.py, backend/modules/assistant/ito/summary.py
This pull request adds a new optional field "tags" to the AssistantOutput classes. The "tags" field allows for categorizing the outputs and can be used for filtering or organizing purposes.
=> feat: Add tags to AssistantOutput classes

backend/modules/assistant/ito/summary.py
=> fix: Fix error message in SummaryAssistant class

backend/modules/brain/integrations/GPT4/Brain.py, backend/modules/brain/knowledge_brain_qa.py
This pull request refactors the GPT4Brain and KnowledgeBrainQA classes to add the functionality of saving non-streaming answers. It includes changes to the `generate_answer` method and the addition of the `save_non_streaming_answer` method. This enhancement improves the overall functionality and performance of the code.
=> fix(gpt4): Refactor GPT4Brain and KnowledgeBrainQA classes to add non-streaming-saving-answer

backend/modules/brain/rags/quivr_rag.py
=> feat(history): max tokens in the history provided

docs/configuring/reranking.mdx, docs/mint.json
This pull request adds a new guide to the documentation that explains how to configure reranking in Quivr. The guide covers the steps to configure the reranking service using the FlashrankRerank library and the Cohere ReRanker. It also provides information on the required environment variables and the default behavior of the Ranker.
=> docs: Add reranking configuration guide

backend/celery_worker.py, backend/main.py, backend/tests/ragas_evaluation/run_evaluation.py
This pull request adds a new telemetry ping task to the celery worker and main.py files. The ping task sends a ping message to the telemetry system.
=> feat: Add telemetry ping task to celery worker and main.py

docs/mint.json
This pull request updates the links in the mint.json file to include a link to the API documentation. The "Blog" link has been replaced with an "API Docs" link that points to https://api.quivr.app/docs.
=> docs: Update links in mint.json to add api

backend/Dockerfile
This pull request updates the Dockerfile to include the installation of the Supabase CLI. The Supabase CLI is required for interacting with the Supabase backend. This update ensures that the Supabase CLI is installed in the Docker image, allowing developers to easily use the Supabase CLI within their Docker environment.
=> feat(docker): Update Dockerfile to install Supabase CLI

frontend/app/assistants/page.tsx, frontend/app/studio/[brainId]/BrainManagementTabs/components/KnowledgeTab/KnowledgeTab.tsx, frontend/app/studio/[brainId]/BrainManagementTabs/components/KnowledgeTab/KnowledgeTable/KnowledgeTable.tsx, frontend/app/studio/[brainId]/BrainManagementTabs/components/SettingsTab/components/ModelSelection/ModelSelection.tsx, frontend/lib/components/AddBrainModal/components/BrainTypeSelectionStep/BrainCatalogue/BrainCatalogue.tsx, frontend/lib/components/AddBrainModal/components/Stepper/Stepper.tsx, frontend/lib/components/ui/BrainCard/BrainCard.tsx
=> fix(frontend): fix some next errors

backend/modules/brain/knowledge_brain_qa.py
This pull request removes the citation metadata from the generate_answer and generate_stream functions. The citation metadata was previously being added to the streamed_chat_history and metadata dictionaries, but it is no longer necessary. This change improves the efficiency and clarity of the code.
=> fix(metadata): Removed citation from metadata

backend/models/settings.py
This pull request adds caching for the Supabase client and database instances in order to improve performance and reduce unnecessary API calls. The `get_supabase_client()` and `get_supabase_db()` functions now check if the instances have already been created and return the cached instances if available. This avoids creating new instances for every function call, resulting in faster execution times.
=> feat(db): Add Supabase client and database instances caching

backend/packages/files/parsers/common.py, docs/configuring/llamaparse.mdx, docs/mint.json
This pull request adds Llama Parse integration for complex document parsing in Quivr. Llama Parse is a tool from Llama Index that allows you to read complex documents in Quivr. It provides an API key that needs to be added to the `.env` file as `LLAMA_CLOUD_API_KEY`. Once configured, you can use the Llama Parse tool to read `pdf`, `docx`, and `doc` files in Quivr.
=> feat(llamaparse): Add Llama Parse integration for complex document parsing

frontend/app/chat/[chatId]/components/ChatDialogueArea/components/ChatDialogue/components/ChatItem/QADisplay/components/MessageRow/components/Citation/Citation.tsx
This pull request fixes the citation handling in the ChatItem component. Previously, if the citation did not contain the word "Content:", the component would throw an error. This PR adds a check for the presence of "Content:" in the citation and handles it accordingly.
=> Fix: citation handling in ChatItem component

backend/modules/chat/service/chat_service.py, backend/modules/notification/service/notification_service.py
=> fix: Refactor chat_service.py and remove unused code

backend/packages/files/parsers/common.py
This pull request fixes the parsing instruction in the common.py file. The result_type has been corrected to "markdown" and the parsing_instruction has been updated to handle checkboxes, tables, and other elements that are hard to parse in a meaningful way.
=> fix: Update parsing instruction in common.py

backend/modules/brain/integrations/GPT4/Brain.py, backend/modules/brain/integrations/Proxy/Brain.py, backend/modules/brain/knowledge_brain_qa.py, frontend/lib/hooks/useAuthModes.ts
This pull request adds a new config parameter to the `conversational_qa_chain` function. The config parameter allows for passing metadata, specifically the conversation ID, to the function. This change ensures that the conversation ID is included in the metadata when invoking the `conversational_qa_chain` function.
=> Add config parameter to conversational_qa_chain

.github/workflows/conventional-pr-title.yml
This pull request updates the PR title linting workflow to use the action-semantic-pull-request@v5 action instead of the conventional-pr-title-action. This change improves the accuracy of the PR title validation process.
=> chore(ci): Update PR title linting workflow

backend/packages/files/parsers/common.py
Delete the replacement of non ASCII characters into spaces
=> fix: utf8 encoding

backend/celery_config.py, backend/modules/assistant/ito/ito.py, backend/modules/assistant/ito/summary.py, backend/modules/assistant/ito/tasks.py
This pull request moves the assistant summary functionality to the celery module for better organization and separation of concerns.
=> feat(celery): moved assistant summary to celery

backend/modules/brain/integrations/GPT4/Brain.py, backend/modules/brain/knowledge_brain_qa.py
This pull request adds a new feature to generate images using the OpenAI DALL-E model. The `ImageGeneratorTool` class is implemented to handle the image generation functionality.
=> feat(gpt4): image generation

backend/modules/brain/integrations/GPT4/Brain.py, backend/modules/tools/__init__.py, backend/modules/tools/url_reader.py
This pull request adds the URLReaderTool to the list of tools in the GPT4Brain class. The URLReaderTool allows for reading the content of a URL.
=> feat(tool): Add URLReaderTool

backend/modules/assistant/ito/ito.py, backend/modules/brain/integrations/GPT4/Brain.py, backend/modules/tools/__init__.py, backend/modules/tools/email_sender.py, backend/modules/tools/image_generator.py, backend/modules/tools/web_search.py
This pull request adds a new email sender tool and updates the image generator tool.
=> feat(email): Add email sender tool and update image generator tool

backend/modules/brain/integrations/GPT4/Brain.py, docs/brains/gpt4.mdx
Updates the GPT-4 documentation and the `GPT4Brain` class to include detailed information about the tools available for GPT4Brain and their use cases.
- **Documentation (`docs/brains/gpt4.mdx`):**
- Adds a new section titled "Tools Available for GPT4Brain" that describes specific tools: WebSearchTool, ImageGeneratorTool, URLReaderTool, and EmailSenderTool.
- Provides use cases for each tool, demonstrating how they can be utilized within GPT4Brain for various scenarios, such as generating images, reading content from URLs, and sending emails.
- **Code (`backend/modules/brain/integrations/GPT4/Brain.py`):**
- Updates the class documentation to include information about the tools available for GPT4Brain and outlines use cases for WebSearchTool, ImageGeneratorTool, URLReaderTool, and …
=> docs: Update GPT4 documentation with available tools and use cases

backend/modules/brain/integrations/Big/Brain.py, backend/modules/brain/integrations/Claude/Brain.py, backend/modules/brain/integrations/GPT4/Brain.py, backend/modules/brain/integrations/Notion/Brain.py, backend/modules/brain/integrations/Proxy/Brain.py
This pull request adds comprehensive docstrings to the Brain classes within the `backend/modules/brain/integrations` directory, enhancing code documentation and readability. The changes include:
- **BigBrain (`Big/Brain.py`)**: Adds a class-level docstring explaining the purpose and functionality of the BigBrain class, along with method-level docstrings detailing the operations performed by each method.
- **ClaudeBrain (`Claude/Brain.py`)**: Introduces a class-level docstring that describes the ClaudeBrain class's integration with the Claude model for conversational AI capabilities, and method-level docstrings that clarify the purpose of each method.
- **GPT4Brain (`GPT4/Brain.py`)**: Updates include a detailed class-level docstring outlining the GPT4Brain's integration with GPT-4 for …
=> docs: Add docstrings to integration brains

backend/models/settings.py, backend/modules/brain/integrations/GPT4/Brain.py, backend/modules/brain/rags/quivr_rag.py, backend/modules/chat/controller/chat_routes.py
This pull request fixes the import statements for OllamaEmbeddings in multiple files. The import statements are updated to use the correct package name "langchain_community.embeddings" instead of "langchain.embeddings.ollama". This ensures that the code can be compiled and executed without any import errors.
=> fix: Update import statements for OllamaEmbeddings

backend/modules/assistant/ito/summary.py, backend/supabase/migrations/20240514080520_rls_optim.sql
This pull request updates the ChatLiteLLM model to "gpt-4o" and adds a row-level security (RLS) optimization for notifications. It also includes a new SQL script to drop and create a policy for allowing user access to all notifications.
=> feat: Update ChatLiteLLM model and add RLS optimization for notifications

backend/modules/brain/service/brain_subscription/resend_invitation_email.py
This pull request fixes the sender email address in the `resend_invitation_email` function in the `resend_invitation_email.py` file. The `from` field has been changed to `sender` to ensure that the correct email address is used when sending the invitation email.
=> fix:  sender email address in resend_invitation_email.py

frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/Editor/MentionsList/MentionItem/MentionItem.module.scss, frontend/app/chat/[chatId]/components/ActionsBar/components/ChatInput/components/ChatEditor/Editor/MentionsList/MentionItem/MentionItem.tsx
Applying dark mode to icons in tiptap.
=> fix(frontend): using dark mode in tiptap

backend/supabase/migrations/20240606170930_sync-reduce-time.sql
=> chore: Set default value for "last_synced" column in "syncs_active" table to '2024-06-01 15:30:25+00'

backend/modules/sync/dto/inputs.py, backend/modules/sync/entity/sync.py, backend/modules/sync/repository/sync.py, backend/modules/sync/repository/sync_files.py, backend/modules/sync/repository/sync_interfaces.py, backend/modules/sync/repository/sync_user.py, backend/modules/sync/service/sync_service.py, backend/modules/sync/utils/googleutils.py, backend/modules/sync/utils/list_files.py, backend/modules/sync/utils/sharepointutils.py, backend/supabase/migrations/20240608095352_supported-sync.sql, backend/tach.yml
This pull request adds support for recursive folder retrieval in the `get_files_folder_user_sync` method. Previously, the method only retrieved files from the specified folder, but now it can also retrieve files from all subfolders recursively. This enhancement improves the functionality and flexibility of the method, allowing for more comprehensive file retrieval in sync operations.
=> fix: integrations

frontend/lib/components/UploadDocumentModal/UploadDocumentModal.module.scss
=> fix(frontend): display bug on add knowledge

backend/modules/sync/controller/sync_routes.py, backend/modules/sync/dto/inputs.py, backend/modules/sync/repository/sync.py, backend/modules/sync/utils/googleutils.py, backend/modules/sync/utils/sharepointutils.py, backend/supabase/migrations/20240610141546_force-sync.sql
This commit adds a new optional boolean field, force_sync, to the SyncsActiveUpdateInput class in the sync module. The force_sync field allows users to manually trigger a sync operation, bypassing the regular sync interval. By default, force_sync is set to False.
The force_sync field is used in the GoogleSyncUtils and AzureSyncUtils classes to determine whether to perform a sync operation even if the regular sync interval has not elapsed. If force_sync is True, the last_synced timestamp is updated and the sync operation is executed.
This enhancement provides more flexibility and control over the synchronization process, allowing users to manually trigger sync operations when needed.
=> feat: Add force_sync option to SyncsActiveUpdateInput

LICENSE, backend/modules/sync/utils/LICENSE
This pull request updates the license to include enterprise features. The license now specifies that certain folders or files within the distribution may be subject to different license terms and conditions, which will be specified in a separate LICENSE file or within the file itself. Additionally, a new Quivr Enterprise license has been added, which restricts the use of the software to production environments only if the user has a valid Quivr Enterprise license for the correct number of user seats. The license also clarifies that modifications and patches to the software can only be used with a valid Quivr Enterprise license. Finally, the license includes a disclaimer of warranties and limitations of liability.
=> Update license to include enterprise features

backend/modules/sync/utils/list_files.py, backend/modules/sync/utils/normalize.py
This commit adds a new utility function `remove_special_characters` to the `normalize.py` module in the `sync/utils` directory. The function removes special characters from file names by normalizing the input string and using regular expressions to remove non-alphanumeric characters.
The function is then used in the `list_files.py` module in the `sync/utils` directory to normalize the names of files retrieved from Google Drive and Azure Drive. This ensures that the file names are free of special characters, improving consistency and compatibility with other parts of the system.
=> feat: Normalize file names in sync module

backend/modules/sync/tasks.py, backend/modules/sync/utils/googleutils.py
This pull request adds error handling for the syncing process in the tasks.py file. Previously, if an error occurred during the syncing process, the program would crash. With this change, any exceptions that occur during syncing will be caught and logged, allowing the program to continue running. This improves the stability and reliability of the syncing functionality.
=> fix: Add error handling for syncing in tasks.py

backend/celery_worker.py, backend/models/databases/supabase/user_usage.py
"This pull request adds a new celery task called `check_if_is_premium_user` that checks if a user is a premium user based on their subscription status. The task retrieves the list of active subscriptions and the list of customers from the Supabase database. It then matches the subscriptions with the customers and updates the user settings with the corresponding premium features if a match is found. If a user is not found or their subscription is expired, the user settings are deleted. This task will run periodically to keep the user settings up to date with the subscription status.
=> feat: Add premium user check in celery task

backend/api/quivr_api/modules/chat/service/chat_service.py, backend/api/quivr_api/modules/chat/tests/test_chats.py, backend/api/quivr_api/modules/dependencies.py
closes #2782.
Changes `sqlalchemy` connection pooling config : 
- **pool_pre_ping=True** : pessimistic disconnect handling. 
> - It is critical to note that the pre-ping approach does not accommodate **for connections dropped in the middle of transactions or other SQL operations** ! But this should only happen if we lose the database either due to network of DB server restart. 
- **pool_size=10**,  with no db side pooling for now, if 6 uvicorn process workers  are spawned (or 6 instances of the backed) we have a pool of 60 processes connecting to the database.
- **pool_recycle=1800** :  Recycles the pool every 30min
Added additional session config : 
- expire_on_commit=False,  When True, all instances will be fully expired after each commit, so that all attribute/object access subsequent …
=> fix: asyncpg pooling config fix

frontend/app/chat/[chatId]/components/ActionsBar/components/KnowledgeToFeed/components/FromDocuments/FromDocuments.module.scss, frontend/lib/components/AddBrainModal/AddBrainModal.module.scss, frontend/lib/components/AddBrainModal/components/BrainMainInfosStep/BrainMainInfosStep.module.scss, frontend/lib/components/AddBrainModal/components/FeedBrainStep/FeedBrainStep.module.scss, frontend/lib/components/AddBrainModal/components/Stepper/Stepper.module.scss, frontend/lib/components/ui/FieldHeader/FieldHeader.module.scss, frontend/lib/components/ui/Modal/Modal.module.scss, frontend/lib/components/ui/Modal/Modal.tsx, frontend/lib/components/ui/QuivrButton/QuivrButton.module.scss, frontend/lib/components/ui/TextInput/TextInput.module.scss
=> feat(frontend): better UI for big modals

.github/workflows/release-please-core.yml, release-please-config.json
This pull request adds the release-please-core workflow and configuration files. The release-please workflow is triggered on push to the main branch and on manual workflow dispatch. It sets up Python, installs Poetry, configures Poetry, and runs release-please for the backend/core package. The release-please configuration file specifies the release type, package name, bump patch for minor pre-major, changelog notes type, include v in tag, tag separator, and component.
=> chore: Add release-please-core workflow and configuration files

backend/core/pyproject.toml
This pull request updates the repository URL in the pyproject.toml file from "https://github.com/langchain-ai/langchain" to "https://github.com/QuivrHQ/quivr".
=> fix(pyproject): fixed to quivr github

.github/workflows/backend-core-tests.yml, backend/core/README.md
This commit adds a new GitHub Actions workflow file `backend-core-tests.yml` to the repository. This workflow is triggered on push and pull request events, specifically for changes made to the `backend/core` directory. The workflow runs tests for the backend/core module using a Tika server as a service. It checks the health of the Tika server before running the tests. The workflow sets up Python, installs dependencies using Poetry, and runs the tests using pytest.
This commit is necessary to automate the testing process for the backend/core module and ensure that the tests are run consistently and reliably.
=> feat: Add GitHub Actions workflow for running tests on backend/core

backend/core/quivr_core/brain.py, backend/core/quivr_core/chat.py, backend/core/quivr_core/config.py, backend/core/quivr_core/models.py, backend/core/quivr_core/quivr_rag.py, backend/core/quivr_core/utils.py, backend/core/tests/conftest.py, backend/core/tests/test_brain.py, backend/core/tests/test_chat_history.py
- Defined quivr-core `ChatHistory`
- `ChatHistory` can be iterated over in tuples of `HumanMessage,AIMessage`
-  Brain appends to the chatHistory once response is received
- Brain holds a dict of chats and defines the default chat (TODO: define a system of selecting the chats)
- Wrote test 
- Updated `QuivrQARAG` to use `ChatHistory` as input
=> feat: quivr core chat history

backend/core/quivr_core/llm/__init__.py, backend/core/tests/test_llm_endpoint.py
llm endpoint model name wasn't taken into account
=> fix: llm model name

.gitignore, backend/core/examples/chatbot/README.md, backend/core/examples/chatbot/chainlit.md, backend/core/examples/chatbot/main.py, backend/core/examples/chatbot/requirements.txt
The commit adds a new Quivr chatbot example to the repository. The example demonstrates how to create a simple chatbot using Quivr and Chainlit. Users can upload a text file and ask questions about its content. The commit includes the necessary files, installation instructions, and usage guidelines.
=> feat: Add Quivr chatbot example

backend/api/quivr_api/modules/notification/dto/inputs.py, backend/api/quivr_api/modules/notification/repository/notifications.py
=> feat: Add bulk_id field to CreateNotification and Notification models

backend/api/quivr_api/celery_monitor.py, backend/api/quivr_api/modules/sync/controller/sync_routes.py, backend/api/quivr_api/modules/sync/utils/googleutils.py
The code changes in `sync_routes.py` update the category for the sync notification from "sync" to "generic". This change ensures that the notification is categorized correctly.
=> feat: Update sync generic bulk

backend/api/quivr_api/modules/sync/controller/sync_routes.py
The code changes in `sync_routes.py` update the category for the sync notification from "sync" to "generic". This change ensures that the notification is categorized correctly.
=> feat: Update sync active notification category

backend/api/quivr_api/modules/chat/dto/chats.py, backend/api/quivr_api/modules/rag_service/utils.py
The Sources class in `chats.py` now includes optional fields for integration and integration link. This allows for better tracking and integration of external sources in the chat module.
=> feat: add integration and integration link to Sources class

backend/api/quivr_api/modules/notification/service/notification_service.py, backend/api/quivr_api/modules/sync/controller/sync_routes.py, backend/api/quivr_api/modules/sync/dto/inputs.py, backend/api/quivr_api/modules/sync/entity/sync.py, backend/api/quivr_api/modules/sync/tasks.py, backend/supabase/migrations/20240726142945_notifications-sync-update.sql
=> feat(notifications): improved requirements

frontend/README.md
=> chore: Update frontend README.md with yarn dev command (#2931)

backend/api/quivr_api/modules/brain/controller/brain_routes.py, backend/api/quivr_api/modules/brain/entity/brain_entity.py, backend/api/quivr_api/modules/chat/controller/chat_routes.py, backend/api/quivr_api/modules/chat_llm_service/chat_llm_service.py, backend/api/quivr_api/packages/utils/uuid_generator.py, backend/core/quivr_core/models.py
=> feat: Add brain_id and brain_name to ChatLLMMetadata model

.gitignore, Makefile, backend/api/quivr_api/modules/models/tests/conftest.py, backend/api/quivr_api/modules/models/tests/test_models.py, backend/api/quivr_api/modules/models/tests/test_models_service.py
=> feat(models): add more tests on service

backend/api/quivr_api/models/settings.py, backend/api/quivr_api/modules/sync/utils/upload.py, backend/core/quivr_core/llm/llm_endpoint.py
=> feat(azure): quivr compatible with it

frontend/Dockerfile
The Dockerfile was modified to include a new environment variable `NEXT_PUBLIC_SHOW_TOKENS` which controls whether tokens should be shown in the frontend. This change was made to enhance the user experience and provide more flexibility in managing token visibility.
Fix ENT-54
=> feat: Add environment variable for showing tokens in frontend

backend/supabase/migrations/20240821201741_brain-knowledge.sql
- Knowledge in vectors with brain_id are exactly the ones in vectors
=> fix : db migrations

frontend/next.config.js
This commit adds two PostHog domains to the Content Security Policy in the next.config.js file. The domains are "*.posthog.com" and "https://us.i.posthog.com".
=> chore: update next.config.js with PostHog domains

backend/api/tests/settings/test_settings.py
=> chore(embeddings): added tests for embeddings

backend/core/examples/save_load_brain.py, backend/core/examples/simple_question.py, backend/core/examples/simple_question_streaming.py, backend/core/quivr_core/brain/brain.py, backend/core/quivr_core/brain/info.py, backend/core/quivr_core/brain/serialization.py, backend/core/quivr_core/files/file.py, backend/core/quivr_core/llm/llm_endpoint.py, backend/core/quivr_core/processor/registry.py, backend/core/quivr_core/quivr_rag_langgraph.py, backend/core/quivr_core/storage/local_storage.py, backend/core/tests/test_brain.py
- Save and load brain to disk: 
```python
async def main():
with tempfile.NamedTemporaryFile(mode="w", suffix=".txt") as temp_file:
temp_file.write("Gold is a liquid of blue-like colour.")
temp_file.flush()
brain = await Brain.afrom_files(name="test_brain", file_paths=[temp_file.name])
save_path = await brain.save("/home/amine/.local/quivr")
brain_loaded = Brain.load(save_path)
brain_loaded.print_info()
```
- Loading all chat history
- Loading from other vector stores, PG for example can be great ...
=> feat: save and load brain

backend/api/quivr_api/modules/sync/entity/sync_models.py
The SyncsUser model in sync_models.py now has an optional status field. This change allows for more flexibility in managing user synchronization status.
=> feat: update SyncsUser status field to be optional

frontend/lib/components/ConnectionCards/ConnectionCards.tsx
The syncNotion function is no longer needed in the ConnectionCards component, so it has been removed. This change simplifies the code and improves maintainability.
=> feat: Remove syncNotion from ConnectionCards

backend/worker/quivr_worker/celery_monitor.py
This commit updates the code in `celery_monitor.py` to handle task success events. When a task with a status of `SUCCESS` is received, it sends a notification with a success status and a corresponding description. Additionally, if the event has a `knowledge_id`, it updates the knowledge status to `UPLOADED`. This change improves the handling of task success events and ensures that notifications and knowledge statuses are properly updated.
Note: This commit message follows the established convention of starting with a verb in the imperative form, followed by a brief description of the changes.
=> feat: Update knowledge status and send notification on task success

frontend/next.config.js
The `next.config.js` file has been modified to update the Content Security Policy (CSP) for PostHog. The CSP now allows requests to any subdomain of `posthog.com` for both `script-src` and `frame-src`. This change ensures that the frontend application can properly communicate with PostHog services.
Co-authored-by: Stan Girard <girard.stanislas@gmail.com>
=> feat: Update Content Security Policy for PostHog

backend/api/quivr_api/models/settings.py, backend/api/quivr_api/modules/knowledge/controller/knowledge_routes.py, backend/api/quivr_api/modules/knowledge/tests/test_knowledge_controller.py, backend/requirements-dev.lock
- file size limit to 50Mb configurable via env
=> feat: kms file size limit

frontend/app/quality-assistant/ProcessTab/ProcessTab.tsx, frontend/lib/components/Menu/components/NotificationsButton/NotificationsButton.tsx, frontend/lib/context/NotificationsProvider/notifications-provider.tsx
=> fix(notifications): added a debouncing mechanism

backend/api/quivr_api/routes/crawl_routes.py, backend/supabase/migrations/20241008154800_check_file.sql
The `crawl_endpoint` function in `crawl_routes.py` now includes the `file_name` property in the `knowledge_to_add` object. This change ensures that the file name is properly associated with the crawled knowledge, improving the accuracy and organization of the data.
Co-authored-by: Stan Girard <girard.stanislas@gmail.com>
=> feat: Add file name to knowledge properties in crawl_endpoint

frontend/app/quality-assistant/AssistantTab/AssistantTab.tsx
=> feat(frontend): add xlsx

backend/api/quivr_api/modules/sync/utils/normalize.py, backend/api/quivr_api/modules/sync/utils/syncutils.py, backend/api/quivr_api/modules/upload/controller/upload_routes.py, backend/core/MegaParse/megaparse/Converter.py, backend/core/MegaParse/megaparse/config.py, backend/core/quivr_core/processor/implementations/megaparse_processor.py, backend/worker/quivr_worker/celery_monitor.py
Our default pdf parser is Unstructured, for which we were using the 'fast' strategy, which fails in parsing some pdf. We instead use the 'auto' strategy which is more flexible and powerful.
Closes TICK-86
=> fix: fixing pdf parsing

backend/api/quivr_api/modules/user/repository/users.py, backend/api/quivr_api/modules/user/service/user_usage.py
Refactor the get_user_credits method in the Users class to improve the calculation of monthly chat credits for a user. This change ensures that the user's monthly chat credit is correctly deducted based on their usage. If no user settings or monthly chat credit is found, a default value of 25 is returned.
=> feat: Improve user credit calculation in get_user_credits

.gitignore, backend/core/quivr_core/base_config.py, backend/core/quivr_core/brain/brain.py, backend/core/quivr_core/chat.py, backend/core/quivr_core/config.py, backend/docs/pyproject.toml
=> docs(fix): fixed warnings from griffe

backend/api/quivr_api/modules/knowledge/dto/inputs.py, backend/api/quivr_api/modules/knowledge/service/knowledge_service.py, backend/api/quivr_api/modules/knowledge/tests/test_knowledge_service.py, backend/api/quivr_api/utils/knowledge_utils.py
=> fix: parsing file extension

examples/chatbot/basic_rag_workflow.yaml, examples/chatbot/main.py
- Added a new file `basic_rag_workflow.yaml` to the `examples/chatbot` directory.
- Configured a standard RAG workflow with multiple nodes and edges.
- Set the maximum number of previous conversation iterations to include in the answer context.
- Added configuration for the LLM (Language Model) with maximum output tokens and temperature.
=> chore(examples): add basic RAG workflow configuration

core/quivr_core/rag/entities/config.py, examples/chatbot/README.md
Instructions in README of example/chatbot is a little out-dated. Updated it to match the latest codebase.
NA
=> docs: Enhance example/chatbot with added instructions

core/quivr_core/rag/quivr_rag_langgraph.py
We fix an error arising when the user input contains no tasks, but only system instructions
=> fix: fixing errors arising when the user input contains no tasks

core/quivr_core/rag/prompts.py, core/quivr_core/rag/quivr_rag_langgraph.py
This will make our answers more robust
=> feat: improving the prompts to always refer to 'tasks' instead of 'questions'

core/pyproject.toml, core/quivr_core/rag/quivr_rag_langgraph.py, core/requirements-dev.lock, core/requirements.lock
Small PR to integrate Langfuse tracing
=> feat: langfuse integration

core/quivr_core/rag/entities/config.py, core/quivr_core/rag/entities/models.py, core/quivr_core/rag/quivr_rag_langgraph.py
By returning a description of each node executed by a (LangGraph) workflow we can show it to the user and thus inform him about the status of the task execution
=> feat: returning a description of each workflow node

core/quivr_core/llm/llm_endpoint.py, core/quivr_core/rag/entities/config.py
We now load all tokenizers at the import of the llm_endpoint module, and any initialisation of the LLMEndpoint class will use the cached tokenizers
Closes ENT-402
=> feat: cache tokenizers

core/quivr_core/llm/llm_endpoint.py
We explicitly load the toeknizers in quivr-api
=> feat: remove tokenizer load

core/pyproject.toml, core/quivr_core/llm/llm_endpoint.py, core/requirements-dev.lock, core/requirements.lock
We limit the number of preloaded tokenizers to 3 and the maximum size to 50 MB
=> feat: limit tokenizers cache size

core/pyproject.toml, core/quivr_core/llm/llm_endpoint.py, core/requirements-dev.lock, core/requirements.lock
We now compute the size of the tokenizer cache using the disk file size of the different tokenizer files
=> feat: remove pympler dependency and add better way to calculate size of tokenizer cache

core/quivr_core/rag/prompts.py
Fix grammar and typo in zendesk prompte template
=> fix: fix grammar and typo in zendesk prompte template

core/pyproject.toml, core/quivr_core/llm/llm_endpoint.py, core/quivr_core/rag/entities/config.py, core/quivr_core/rag/quivr_rag_langgraph.py
Introduce support for the Gemini model in the language model configuration, allowing users to utilize Gemini alongside existing models. Update the configuration to include Gemini-specific settings and ensure compatibility with the overall architecture.
=> feat: Add Gemini support for language models
